#theme: jekyll-theme-hacker
remote_theme: b2a3e8/jekyll-theme-console
title: Inner Machinations
description: My place for writing about things I find interesting.
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true